# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: myP@ssword
      POSTGRES_ROOT_PASSWORD: myP@ssword
      POSTGRES_DB: nextapp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080